# Generated by Django 3.1.5 on 2021-01-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choide',
            new_name='Choice',
        ),
    ]
